### ISSUE TITLE
Chain.jl instead of DataFramesMeta.jl

### ISSUE THREAD

**Issue by dmbates** [RePsychLing/SMLP2021#10]
I propose that we standardize on using Julius Krumbiegel's [Chain](https://github.com/jkrumbiegel/Chain.jl) package instead of [DataFramesMeta](https://github.com/JuliaData/DataFramesMeta.jl].  `Chain` is more flexible and it means only needing to learn one macro.

I can make the substitutions in the notebooks if this idea is accepted.

**Comment by kliegl** [comment]
That would be great.

**Comment by palday** [comment]
Closed by #11
