### ISSUE TITLE
Use the AlgebraOfGraphics plots in the tutorial notebooks?

### ISSUE THREAD

**Issue by dmbates** [RePsychLing/SMLP2021#4]
Shall we change the tutorial notebooks to use the `AlgebraOfGraphics` plots instead of displaying a .png?

**Comment by kliegl** [comment]
Not until I know how to relevel factors and relabel levels; and not in its current form. I really don't like the looks of them. They don't have to be identical to ggplot2 figures, but they should be as appealing or ideally even more appealing.  I can see that we will get there by September, but I think there is ways to go.

**Comment by dmbates** [comment]
There was a miscommunication between Jacob Quinn and me regarding merging the pull request I made for defining `refarray`, `refpool`, and `levels` for the `DictEncoded` type.  He thought I was going to do it and I thought he was going to do it.  We got this resolved yesterday so that Arrow v1.4.0 preserves the original order. In general I don't think you should depend on this unless the factor is marked as `ordered`,  If you are going to depend on a specific order of the levels of a factor for the contrasts that you use it would be a good idea to use an ordered factor.  It happens that there is not much support for ordered factors right now, except in CategoricalArrays but that support can be added to Arrow and PooledArrays.

```julia
julia> using Arrow, DataAPI, Pkg

julia> Pkg.status("Arrow")
      Status `~/.julia/environments/v1.7/Project.toml`
  [69666777] Arrow v1.4.0

julia> tbl = Arrow.Table("/home/bates/git/SMLP2021/notebooks/data/fggk21.arrow")
Arrow.Table with 525126 rows, 10 columns, and schema:
 :Cohort    String
 :District  String
 :BU        String
 :School    String
 :Child     String
 :Sex       String
 :age       Float64
 :Test      String
 :score     Float64
 :zScore    Float64

julia> DataAPI.refpool(tbl.Test)
5-element Vector{String}:
 "Run"
 "Star_r"
 "S20_r"
 "SLJ"
 "BPT"

julia> DataAPI.levels(tbl.Test)
5-element Vector{String}:
 "Run"
 "Star_r"
 "S20_r"
 "SLJ"
 "BPT"
```

The distinction between `refpool` and `levels` is that `refpool` returns `nothing` by default (i.e. if no specific method has been defined) whereas `levels` by default returns the sorted unique values.  Also, if missing values are allowed in the array then `refpool` includes `missing` but `levels` doesn't.

**Comment by kliegl** [comment]
I solved the levels problem; see the pushed version in AoGPlots.jl

```
begin
	dat = DataFrame(Arrow.Table("./data/fggk21.arrow"));
	dat.Test = dat.Test |> categorical;
	recode!(dat.Test, 
            "Run" => "Endurance", 
		    "Star_r" => "Coordination",
		    "S20_r" => "Speed",
		    "SLJ" => "PowerLOW",
		    "BPT" => "PowerUP");
	dat.Sex = dat.Sex |> categorical;
	recode!(dat.Sex, "male" => "Boys",  "female" => "Girls");
	describe(dat)
end
```

Also the coloring of lines and points.

```
begin
	using AlgebraOfGraphics: linear
	design1 = mapping(:age, :zScore, linetype = :Sex, layout_x = :Test)
	design2 = mapping(:Age, :zScore, color = :Sex, layout_x = :Test)
	lines = design1 * linear
	means = design2 * visual(Scatter, color= [:blue, :red], markersize=(6))
	data(df) * means + data(dat) * lines |> draw
end
```

Only thing left is how to specify axis attributes and moving legend into the plot. Then I would be happy to merge.

**Comment by dmbates** [comment]
If you have the `DataFrames` package loaded you can use `recode` to change the levels.  Try
```julia
julia> tbl.test1 = recode(tbl.Test,
     "Run" => "Endurance",
    "Star_r" => "Coordination",
    "S20_r" => "Speed",
    "SLJ" => "LowerBody",
    "BPT" => "UpperBody")
```

**Comment by kliegl** [comment]
I already did!

**Comment by kliegl** [comment]
It seems all the info I want is described at this page:

https://github.com/JuliaPlots/AlgebraOfGraphics.jl/blob/master/examples/gui.jl

However, I don't seem to find the right way to specify them in our example.

**Comment by kliegl** [comment]
I also tried to understand this page:
http://juliaplots.org/AlgebraOfGraphics.jl/dev/generated/internals/

**Comment by dmbates** [comment]
> It seems all the info I want is described at this page:
> 
> https://github.com/JuliaPlots/AlgebraOfGraphics.jl/blob/master/examples/gui.jl
> 
> However, I don't seem to find the right way to specify them in our example. I actually can't get the example run because it does not find: layoutplot! (under using AoG)

I think you need the first couple of lines
```julia
using AbstractPlotting
using AbstractPlotting.MakieLayout
```

`Makie` is an extensive plotting infrastructure.  It provides different plotting backends like `GLMakie` to use graphics cards, if you have one, `CairoMakie` for various graphics formats, and `WGLMakie` for interactive graphics in a browser.  The `MakieLayout` package is what is used for the `layout_x` specifications.

**Comment by kliegl** [comment]
I am pretty sure I tried what you recommend and I did some reading on the various backends, too.

**Comment by kliegl** [comment]
I can adjust the x-axis ticks when I define the figure bottom up. I thought it would go into one of the mapping() functions. I also tried to generate a separate line object (something like style = line(...)  and multiply or add it to the final line.  I am sure there is a solution, but I am down to too much trial and error now. I will work on something else for the rest of the day.

**Comment by kliegl** [comment]
One more attempt I saw by someone who seemed to struggle with the same or similar problems is the package `TabularMakie.jl`; it is also built on AoG. 

https://github.com/greimel/TabularMakie.jl

**Comment by kliegl** [comment]
If I can't figure out how to access/modify the axis and legend features in the AoG code we have, then I think I can generate the graphs in the Makie Ecosystem, basically implementing the faceting by hand.  The tutorials and documentation @ http://makie.juliaplots.org/stable/  are really quite good. 

The alternative could be a MixedModels.jl recipe with Plots.jl, but this might be an option for later.  The field seems to move toward Makie

I will have to work on other things today.

**Comment by kliegl** [comment]
@dmbates I think we can close this issue.
