### ISSUE TITLE
update HTML of Pluto notebooks

### ISSUE THREAD

**Issue by kliegl** [RePsychLing/SMLP2021#59]
@palday Could we update the HTMLs of the `mmt_x.jl` Pluto notebooks we link to from https://github.com/RePsychLing/SMLP2021 ?  I assume this is done from your branch https://github.com/RePsychLing/SMLP2021/tree/pa/htmlautogen, but I don't know how to make this happen.  Should we merge this branch into main?

PS: Perhaps we should also update to recommend Julia 1.7.0_rc, because that's what we use in the notebooks. Although I think they also work with 1.6.2. So we may want to wait until the final release.

**Comment by palday** [comment]
The HTML output is updated every time a PR is merged into `main`, though it does take a while because it has to run *all* the notebooks sequentially on a shared resource. I can update the bot to use Julia 1.7, but I would prefer to wait for the official release. :smile:
